version: '3'

services:
  app:
    container_name: go-server-api
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./databases/sqlite3:/app/databases/sqlite3
      - ./logs:/app/logs
      - ./outputs:/app/outputs
    ports:
      - "8080:8080"