version: '3'

services:
  app-server:
    container_name: go-server-api
    build: 
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./databases/sqlite3:/app/databases/sqlite3
      - ./logs:/app/logs
    ports:
      - "8080:8080"

networks:
  go-network:
    external: true
